import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    id: uuid(),
    product_name: "hendrerit at vulputate",
    brand: "Gucci",
    category: "Accessories",
    price: 591.98,
    color: "Fuscia",
    size: "XS",
    material: "Silk",
    season: "Fall",
    image_url:
      "http://newyorker.com/tincidunt/in/leo/maecenas/pulvinar/lobortis/est.json",
    description:
      "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "nisi nam ultrices libero",
    brand: "Nike",
    category: "Shoes",
    price: 26.32,
    color: "Turquoise",
    size: "M",
    material: "Cotton",
    season: "Fall",
    image_url: "https://topsy.com/lobortis/convallis/tortor/risus.jpg",
    description:
      "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "dolor sit amet consectetuer",
    brand: "Gucci",
    category: "Accessories",
    price: 703.97,
    color: "Aquamarine",
    size: "S",
    material: "Denim",
    season: "Winter",
    image_url: "https://reverbnation.com/rutrum.json",
    description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "maecenas pulvinar lobortis est phasellus",
    brand: "Zara",
    category: "Shoes",
    price: 413.86,
    color: "Green",
    size: "M",
    material: "Leather",
    season: "Summer",
    image_url: "http://foxnews.com/nec/nisi/volutpat/eleifend/donec/ut.aspx",
    description:
      "Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "non sodales",
    brand: "Adidas",
    category: "Accessories",
    price: 242.25,
    color: "Red",
    size: "XL",
    material: "Silk",
    season: "Summer",
    image_url: "https://google.com.br/libero/convallis/eget/eleifend.json",
    description:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "interdum venenatis turpis enim",
    brand: "Zara",
    category: "Clothing",
    price: 813.84,
    color: "Yellow",
    size: "L",
    material: "Leather",
    season: "Winter",
    image_url: "http://sun.com/bibendum.xml",
    description:
      "Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "nulla eget eros elementum pellentesque",
    brand: "Adidas",
    category: "Accessories",
    price: 264.97,
    color: "Violet",
    size: "L",
    material: "Cotton",
    season: "Spring",
    image_url: "https://mozilla.org/a.js",
    description:
      "Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "volutpat convallis morbi odio odio",
    brand: "Adidas",
    category: "Shoes",
    price: 658.68,
    color: "Green",
    size: "S",
    material: "Cotton",
    season: "Winter",
    image_url: "http://yellowbook.com/consequat/varius.html",
    description:
      "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "tempus",
    brand: "Adidas",
    category: "Shoes",
    price: 387.31,
    color: "Blue",
    size: "S",
    material: "Leather",
    season: "Spring",
    image_url: "https://yahoo.co.jp/nisi/eu/orci/mauris/lacinia.jpg",
    description:
      "Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "nunc",
    brand: "Zara",
    category: "Shoes",
    price: 205.35,
    color: "Goldenrod",
    size: "M",
    material: "Cotton",
    season: "Summer",
    image_url: "https://slideshare.net/morbi/ut/odio/cras.jpg",
    description:
      "Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "vel",
    brand: "Zara",
    category: "Accessories",
    price: 381.04,
    color: "Teal",
    size: "M",
    material: "Silk",
    season: "Winter",
    image_url:
      "http://globo.com/vestibulum/ante/ipsum/primis/in/faucibus/orci.jsp",
    description:
      "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "ultrices phasellus id sapien in",
    brand: "Zara",
    category: "Shoes",
    price: 933.79,
    color: "Goldenrod",
    size: "L",
    material: "Leather",
    season: "Summer",
    image_url:
      "http://typepad.com/faucibus/orci/luctus/et/ultrices/posuere/cubilia.jsp",
    description:
      "Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "justo in blandit ultrices enim",
    brand: "Gucci",
    category: "Shoes",
    price: 759.77,
    color: "Turquoise",
    size: "L",
    material: "Denim",
    season: "Spring",
    image_url: "https://creativecommons.org/mi.jsp",
    description:
      "Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "dolor",
    brand: "Adidas",
    category: "Clothing",
    price: 709.51,
    color: "Pink",
    size: "L",
    material: "Cotton",
    season: "Fall",
    image_url: "http://cisco.com/mi/nulla/ac/enim/in/tempor.xml",
    description:
      "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "justo nec",
    brand: "Adidas",
    category: "Accessories",
    price: 884.45,
    color: "Orange",
    size: "XS",
    material: "Denim",
    season: "Fall",
    image_url:
      "http://mayoclinic.com/justo/in/hac/habitasse/platea/dictumst.html",
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "elementum pellentesque",
    brand: "Adidas",
    category: "Shoes",
    price: 317.07,
    color: "Goldenrod",
    size: "XS",
    material: "Silk",
    season: "Spring",
    image_url: "http://census.gov/justo.aspx",
    description:
      "Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "ac consequat metus sapien",
    brand: "Adidas",
    category: "Accessories",
    price: 309.33,
    color: "Khaki",
    size: "M",
    material: "Cotton",
    season: "Fall",
    image_url:
      "http://sphinn.com/rutrum/at/lorem/integer/tincidunt/ante/vel.json",
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "consectetuer eget",
    brand: "Adidas",
    category: "Shoes",
    price: 277.77,
    color: "Yellow",
    size: "M",
    material: "Silk",
    season: "Winter",
    image_url: "http://amazon.co.jp/nisi/volutpat/eleifend/donec/ut/dolor.xml",
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "tristique est et tempus",
    brand: "Zara",
    category: "Accessories",
    price: 641.79,
    color: "Red",
    size: "XS",
    material: "Denim",
    season: "Winter",
    image_url: "https://usatoday.com/condimentum/id.aspx",
    description:
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "turpis",
    brand: "Nike",
    category: "Clothing",
    price: 353.53,
    color: "Goldenrod",
    size: "L",
    material: "Silk",
    season: "Summer",
    image_url: "http://pen.io/tellus/nulla/ut/erat/id/mauris.js",
    description:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "a pede posuere",
    brand: "Gucci",
    category: "Shoes",
    price: 411.74,
    color: "Maroon",
    size: "L",
    material: "Denim",
    season: "Winter",
    image_url: "http://who.int/euismod/scelerisque/quam/turpis.png",
    description:
      "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "quam fringilla",
    brand: "Adidas",
    category: "Clothing",
    price: 732.51,
    color: "Green",
    size: "XL",
    material: "Leather",
    season: "Fall",
    image_url: "https://myspace.com/vestibulum/ante/ipsum/primis/in.js",
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "nullam",
    brand: "Nike",
    category: "Clothing",
    price: 227.89,
    color: "Violet",
    size: "S",
    material: "Silk",
    season: "Spring",
    image_url: "https://odnoklassniki.ru/semper/rutrum/nulla/nunc.aspx",
    description:
      "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "varius ut blandit non",
    brand: "Zara",
    category: "Shoes",
    price: 184.15,
    color: "Khaki",
    size: "M",
    material: "Silk",
    season: "Fall",
    image_url: "http://uol.com.br/diam/vitae/quam/suspendisse/potenti.aspx",
    description:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "imperdiet et commodo vulputate justo",
    brand: "Adidas",
    category: "Clothing",
    price: 767.14,
    color: "Goldenrod",
    size: "XS",
    material: "Leather",
    season: "Winter",
    image_url:
      "https://feedburner.com/tempus/vel/pede/morbi/porttitor/lorem.json",
    description:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "purus",
    brand: "Zara",
    category: "Clothing",
    price: 521.7,
    color: "Red",
    size: "L",
    material: "Silk",
    season: "Spring",
    image_url: "https://amazon.co.uk/sapien.aspx",
    description:
      "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "ut erat curabitur gravida nisi",
    brand: "Adidas",
    category: "Accessories",
    price: 126.97,
    color: "Khaki",
    size: "L",
    material: "Silk",
    season: "Summer",
    image_url: "http://amazon.co.jp/consequat.html",
    description:
      "Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "vestibulum ac est lacinia",
    brand: "Adidas",
    category: "Accessories",
    price: 277.0,
    color: "Violet",
    size: "L",
    material: "Cotton",
    season: "Spring",
    image_url: "https://symantec.com/sapien/arcu/sed/augue/aliquam/erat.jpg",
    description:
      "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "arcu",
    brand: "Gucci",
    category: "Accessories",
    price: 290.34,
    color: "Yellow",
    size: "S",
    material: "Leather",
    season: "Winter",
    image_url: "http://apache.org/tincidunt.html",
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "posuere",
    brand: "Adidas",
    category: "Clothing",
    price: 691.28,
    color: "Fuscia",
    size: "S",
    material: "Denim",
    season: "Winter",
    image_url: "https://un.org/non/ligula/pellentesque/ultrices/phasellus.aspx",
    description:
      "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "velit nec nisi vulputate",
    brand: "Nike",
    category: "Accessories",
    price: 180.55,
    color: "Goldenrod",
    size: "XS",
    material: "Silk",
    season: "Spring",
    image_url: "https://bloglines.com/quis/turpis/sed/ante/vivamus/tortor.json",
    description:
      "In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "faucibus orci luctus et",
    brand: "Nike",
    category: "Accessories",
    price: 641.73,
    color: "Puce",
    size: "M",
    material: "Cotton",
    season: "Winter",
    image_url: "https://mysql.com/condimentum/curabitur.json",
    description:
      "Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "sit amet lobortis",
    brand: "Adidas",
    category: "Accessories",
    price: 804.78,
    color: "Puce",
    size: "XS",
    material: "Denim",
    season: "Summer",
    image_url: "https://mediafire.com/nisi/eu.aspx",
    description:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "ligula nec sem duis",
    brand: "Zara",
    category: "Accessories",
    price: 267.53,
    color: "Pink",
    size: "L",
    material: "Silk",
    season: "Summer",
    image_url: "http://illinois.edu/ornare.js",
    description:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "in",
    brand: "Zara",
    category: "Shoes",
    price: 189.55,
    color: "Orange",
    size: "XS",
    material: "Leather",
    season: "Spring",
    image_url: "http://shop-pro.jp/venenatis.js",
    description:
      "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "cubilia curae",
    brand: "Nike",
    category: "Shoes",
    price: 573.81,
    color: "Turquoise",
    size: "XL",
    material: "Denim",
    season: "Summer",
    image_url: "https://tiny.cc/interdum/eu/tincidunt/in.xml",
    description:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "vel nisl duis ac",
    brand: "Gucci",
    category: "Clothing",
    price: 747.76,
    color: "Orange",
    size: "L",
    material: "Cotton",
    season: "Winter",
    image_url: "https://boston.com/ante.js",
    description:
      "Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "nulla ut",
    brand: "Gucci",
    category: "Accessories",
    price: 414.23,
    color: "Indigo",
    size: "M",
    material: "Leather",
    season: "Summer",
    image_url: "http://cargocollective.com/maecenas.xml",
    description:
      "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "nullam porttitor lacus",
    brand: "Adidas",
    category: "Accessories",
    price: 67.11,
    color: "Aquamarine",
    size: "S",
    material: "Cotton",
    season: "Spring",
    image_url: "https://mac.com/ut.aspx",
    description:
      "Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "lobortis",
    brand: "Zara",
    category: "Clothing",
    price: 357.76,
    color: "Maroon",
    size: "XL",
    material: "Leather",
    season: "Summer",
    image_url: "https://senate.gov/ut/at/dolor/quis/odio/consequat.png",
    description:
      "Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "rutrum ac lobortis",
    brand: "Nike",
    category: "Accessories",
    price: 229.06,
    color: "Goldenrod",
    size: "S",
    material: "Silk",
    season: "Winter",
    image_url:
      "https://creativecommons.org/ut/blandit/non/interdum/in/ante.jpg",
    description:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "in blandit ultrices",
    brand: "Adidas",
    category: "Accessories",
    price: 919.82,
    color: "Indigo",
    size: "L",
    material: "Leather",
    season: "Summer",
    image_url: "http://miibeian.gov.cn/posuere/cubilia/curae.aspx",
    description:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "adipiscing elit",
    brand: "Adidas",
    category: "Shoes",
    price: 122.92,
    color: "Fuscia",
    size: "XS",
    material: "Leather",
    season: "Spring",
    image_url: "http://samsung.com/eleifend/donec/ut/dolor.json",
    description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "ut erat id mauris",
    brand: "Zara",
    category: "Clothing",
    price: 137.57,
    color: "Blue",
    size: "XL",
    material: "Cotton",
    season: "Summer",
    image_url: "http://nsw.gov.au/vel/augue/vestibulum/ante/ipsum.png",
    description:
      "Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "posuere cubilia curae mauris",
    brand: "Gucci",
    category: "Clothing",
    price: 564.98,
    color: "Aquamarine",
    size: "XL",
    material: "Cotton",
    season: "Fall",
    image_url: "https://com.com/eu/magna/vulputate/luctus/cum.json",
    description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "ut",
    brand: "Adidas",
    category: "Accessories",
    price: 656.7,
    color: "Orange",
    size: "XL",
    material: "Denim",
    season: "Winter",
    image_url: "http://friendfeed.com/vel/ipsum/praesent.xml",
    description:
      "Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "neque",
    brand: "Zara",
    category: "Clothing",
    price: 316.62,
    color: "Fuscia",
    size: "XS",
    material: "Denim",
    season: "Spring",
    image_url: "https://free.fr/at/nibh.aspx",
    description:
      "Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "maecenas leo odio condimentum id",
    brand: "Zara",
    category: "Accessories",
    price: 204.15,
    color: "Turquoise",
    size: "XL",
    material: "Cotton",
    season: "Fall",
    image_url: "http://unesco.org/vivamus/vestibulum/sagittis/sapien.jsp",
    description:
      "Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "ipsum dolor sit amet consectetuer",
    brand: "Gucci",
    category: "Clothing",
    price: 322.8,
    color: "Puce",
    size: "XL",
    material: "Leather",
    season: "Winter",
    image_url: "http://indiatimes.com/ut/mauris/eget/massa/tempor.jpg",
    description:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "turpis donec posuere",
    brand: "Adidas",
    category: "Accessories",
    price: 566.11,
    color: "Goldenrod",
    size: "XS",
    material: "Leather",
    season: "Fall",
    image_url: "https://sun.com/nibh/ligula/nec/sem.jpg",
    description:
      "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "ac est",
    brand: "Nike",
    category: "Accessories",
    price: 379.97,
    color: "Blue",
    size: "S",
    material: "Cotton",
    season: "Summer",
    image_url:
      "http://deviantart.com/in/hac/habitasse/platea/dictumst/maecenas.png",
    description:
      "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "iaculis diam erat fermentum",
    brand: "Nike",
    category: "Accessories",
    price: 240.53,
    color: "Fuscia",
    size: "M",
    material: "Leather",
    season: "Spring",
    image_url: "http://com.com/sociis.png",
    description:
      "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "nulla ut",
    brand: "Zara",
    category: "Shoes",
    price: 444.96,
    color: "Pink",
    size: "L",
    material: "Silk",
    season: "Spring",
    image_url: "http://wiley.com/amet/eleifend.html",
    description:
      "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "blandit nam nulla integer",
    brand: "Adidas",
    category: "Accessories",
    price: 869.59,
    color: "Aquamarine",
    size: "S",
    material: "Leather",
    season: "Fall",
    image_url: "https://un.org/curae/duis/faucibus.html",
    description:
      "Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "ac diam cras pellentesque",
    brand: "Zara",
    category: "Clothing",
    price: 122.48,
    color: "Mauv",
    size: "S",
    material: "Cotton",
    season: "Fall",
    image_url: "https://sfgate.com/integer/a.json",
    description:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "magna vestibulum aliquet ultrices erat",
    brand: "Gucci",
    category: "Accessories",
    price: 271.98,
    color: "Puce",
    size: "M",
    material: "Denim",
    season: "Fall",
    image_url: "https://ibm.com/mauris/non/ligula/pellentesque/ultrices.jsp",
    description:
      "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "integer aliquet massa id",
    brand: "Adidas",
    category: "Shoes",
    price: 956.18,
    color: "Maroon",
    size: "XL",
    material: "Leather",
    season: "Winter",
    image_url: "https://phpbb.com/quis/libero.png",
    description:
      "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "sit amet sapien dignissim",
    brand: "Zara",
    category: "Accessories",
    price: 16.23,
    color: "Goldenrod",
    size: "S",
    material: "Silk",
    season: "Fall",
    image_url: "https://hc360.com/lorem/vitae/mattis/nibh/ligula/nec.jsp",
    description:
      "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "luctus et ultrices",
    brand: "Nike",
    category: "Shoes",
    price: 124.47,
    color: "Mauv",
    size: "M",
    material: "Leather",
    season: "Winter",
    image_url: "http://dyndns.org/libero/nam/dui/proin/leo.html",
    description:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "ut massa",
    brand: "Gucci",
    category: "Shoes",
    price: 706.45,
    color: "Puce",
    size: "M",
    material: "Leather",
    season: "Winter",
    image_url: "https://amazonaws.com/commodo/vulputate/justo.jpg",
    description:
      "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "quisque porta volutpat erat",
    brand: "Adidas",
    category: "Accessories",
    price: 224.65,
    color: "Aquamarine",
    size: "XS",
    material: "Denim",
    season: "Winter",
    image_url: "https://techcrunch.com/tortor/id/nulla/ultrices/aliquet.aspx",
    description:
      "Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "curabitur gravida nisi at",
    brand: "Nike",
    category: "Accessories",
    price: 577.49,
    color: "Khaki",
    size: "S",
    material: "Silk",
    season: "Spring",
    image_url:
      "https://tripod.com/orci/luctus/et/ultrices/posuere/cubilia.aspx",
    description:
      "Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "nullam orci",
    brand: "Zara",
    category: "Accessories",
    price: 895.22,
    color: "Goldenrod",
    size: "S",
    material: "Silk",
    season: "Spring",
    image_url: "http://about.me/diam/vitae/quam/suspendisse/potenti.xml",
    description:
      "Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "risus dapibus augue vel accumsan",
    brand: "Adidas",
    category: "Clothing",
    price: 715.66,
    color: "Blue",
    size: "XS",
    material: "Denim",
    season: "Summer",
    image_url: "http://fda.gov/nibh.png",
    description:
      "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "mattis pulvinar nulla pede ullamcorper",
    brand: "Adidas",
    category: "Clothing",
    price: 700.35,
    color: "Goldenrod",
    size: "L",
    material: "Silk",
    season: "Summer",
    image_url: "http://mashable.com/auctor/sed/tristique/in/tempus.jpg",
    description:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "nulla sed vel",
    brand: "Gucci",
    category: "Shoes",
    price: 509.63,
    color: "Red",
    size: "L",
    material: "Silk",
    season: "Fall",
    image_url: "https://altervista.org/aliquam.html",
    description:
      "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "id ornare",
    brand: "Gucci",
    category: "Shoes",
    price: 714.05,
    color: "Khaki",
    size: "XL",
    material: "Silk",
    season: "Winter",
    image_url: "http://patch.com/ac.jpg",
    description:
      "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "mauris morbi non",
    brand: "Zara",
    category: "Clothing",
    price: 887.0,
    color: "Indigo",
    size: "XL",
    material: "Silk",
    season: "Spring",
    image_url: "http://clickbank.net/aliquam/quis/turpis.jsp",
    description:
      "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "aliquam augue",
    brand: "Zara",
    category: "Clothing",
    price: 979.64,
    color: "Red",
    size: "XL",
    material: "Denim",
    season: "Fall",
    image_url: "http://japanpost.jp/sapien/placerat/ante/nulla/justo.html",
    description:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "sed nisl nunc",
    brand: "Nike",
    category: "Clothing",
    price: 10.75,
    color: "Red",
    size: "XS",
    material: "Cotton",
    season: "Winter",
    image_url:
      "https://chicagotribune.com/magnis/dis/parturient/montes/nascetur/ridiculus.png",
    description:
      "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "ac consequat metus sapien",
    brand: "Gucci",
    category: "Shoes",
    price: 778.98,
    color: "Yellow",
    size: "L",
    material: "Denim",
    season: "Winter",
    image_url: "https://about.com/donec/semper/sapien/a/libero/nam/dui.js",
    description:
      "Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "orci luctus",
    brand: "Adidas",
    category: "Accessories",
    price: 33.71,
    color: "Orange",
    size: "L",
    material: "Cotton",
    season: "Winter",
    image_url: "http://psu.edu/nulla/tellus/in/sagittis/dui/vel/nisl.aspx",
    description:
      "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "cras in",
    brand: "Zara",
    category: "Accessories",
    price: 984.12,
    color: "Purple",
    size: "XS",
    material: "Leather",
    season: "Winter",
    image_url: "http://webeden.co.uk/blandit/mi/in/porttitor/pede.html",
    description:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "odio donec vitae nisi",
    brand: "Gucci",
    category: "Accessories",
    price: 720.5,
    color: "Pink",
    size: "L",
    material: "Denim",
    season: "Summer",
    image_url: "https://alexa.com/felis/ut/at/dolor/quis/odio.png",
    description:
      "Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "cras",
    brand: "Zara",
    category: "Shoes",
    price: 275.82,
    color: "Puce",
    size: "XL",
    material: "Cotton",
    season: "Winter",
    image_url: "http://walmart.com/habitasse/platea/dictumst.png",
    description:
      "Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "vel est donec",
    brand: "Zara",
    category: "Accessories",
    price: 279.48,
    color: "Puce",
    size: "XS",
    material: "Leather",
    season: "Spring",
    image_url: "http://bbc.co.uk/convallis.aspx",
    description:
      "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "volutpat",
    brand: "Gucci",
    category: "Clothing",
    price: 111.54,
    color: "Crimson",
    size: "XS",
    material: "Cotton",
    season: "Fall",
    image_url: "https://yale.edu/natoque.js",
    description:
      "Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "libero quis orci",
    brand: "Adidas",
    category: "Shoes",
    price: 931.94,
    color: "Teal",
    size: "S",
    material: "Cotton",
    season: "Spring",
    image_url: "https://freewebs.com/sit/amet.xml",
    description:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "semper",
    brand: "Gucci",
    category: "Shoes",
    price: 760.26,
    color: "Green",
    size: "XL",
    material: "Denim",
    season: "Spring",
    image_url: "http://craigslist.org/eu/massa/donec/dapibus/duis/at/velit.xml",
    description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "tincidunt eu felis fusce posuere",
    brand: "Nike",
    category: "Accessories",
    price: 484.24,
    color: "Blue",
    size: "M",
    material: "Denim",
    season: "Fall",
    image_url:
      "http://cdc.gov/pede/ac/diam/cras/pellentesque/volutpat/dui.json",
    description:
      "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "auctor gravida sem praesent",
    brand: "Nike",
    category: "Clothing",
    price: 938.71,
    color: "Violet",
    size: "XL",
    material: "Denim",
    season: "Summer",
    image_url: "https://posterous.com/donec.json",
    description:
      "Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "semper interdum",
    brand: "Zara",
    category: "Accessories",
    price: 905.44,
    color: "Aquamarine",
    size: "L",
    material: "Denim",
    season: "Summer",
    image_url:
      "http://earthlink.net/augue/quam/sollicitudin/vitae/consectetuer/eget/rutrum.js",
    description:
      "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "ut volutpat sapien",
    brand: "Adidas",
    category: "Shoes",
    price: 291.37,
    color: "Violet",
    size: "XL",
    material: "Denim",
    season: "Spring",
    image_url: "https://tripod.com/aliquam/quis/turpis/eget/elit.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "quam a odio",
    brand: "Zara",
    category: "Accessories",
    price: 617.18,
    color: "Orange",
    size: "M",
    material: "Denim",
    season: "Fall",
    image_url: "https://boston.com/proin/eu/mi/nulla/ac/enim.xml",
    description:
      "Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "turpis adipiscing lorem vitae",
    brand: "Nike",
    category: "Clothing",
    price: 513.49,
    color: "Purple",
    size: "L",
    material: "Silk",
    season: "Winter",
    image_url: "https://google.pl/felis.json",
    description:
      "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "nisi eu orci",
    brand: "Nike",
    category: "Accessories",
    price: 974.13,
    color: "Blue",
    size: "S",
    material: "Cotton",
    season: "Fall",
    image_url: "http://wiley.com/erat/quisque/erat/eros/viverra.js",
    description:
      "Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "vestibulum ante",
    brand: "Zara",
    category: "Shoes",
    price: 732.28,
    color: "Green",
    size: "XL",
    material: "Leather",
    season: "Winter",
    image_url: "http://apple.com/vestibulum/eget.jpg",
    description:
      "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "nec molestie sed justo",
    brand: "Adidas",
    category: "Clothing",
    price: 491.72,
    color: "Orange",
    size: "XS",
    material: "Leather",
    season: "Summer",
    image_url: "https://uiuc.edu/augue/a/suscipit/nulla/elit/ac/nulla.html",
    description:
      "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "massa tempor convallis",
    brand: "Gucci",
    category: "Clothing",
    price: 263.23,
    color: "Indigo",
    size: "S",
    material: "Leather",
    season: "Winter",
    image_url:
      "http://washingtonpost.com/erat/vestibulum/sed/magna/at/nunc/commodo.xml",
    description:
      "Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "eu massa donec dapibus duis",
    brand: "Adidas",
    category: "Clothing",
    price: 565.38,
    color: "Purple",
    size: "L",
    material: "Leather",
    season: "Summer",
    image_url: "https://ucla.edu/leo/odio/porttitor/id/consequat/in.xml",
    description:
      "Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.",
    rating: 3,
  },
  {
    id: uuid(),
    product_name: "ornare consequat lectus",
    brand: "Adidas",
    category: "Shoes",
    price: 391.72,
    color: "Indigo",
    size: "S",
    material: "Cotton",
    season: "Winter",
    image_url: "https://amazonaws.com/rutrum/neque/aenean/auctor/gravida.json",
    description:
      "Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "libero nullam",
    brand: "Adidas",
    category: "Shoes",
    price: 768.06,
    color: "Mauv",
    size: "L",
    material: "Denim",
    season: "Fall",
    image_url: "http://bbc.co.uk/malesuada/in.aspx",
    description:
      "Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "lacinia sapien",
    brand: "Gucci",
    category: "Clothing",
    price: 691.11,
    color: "Aquamarine",
    size: "XL",
    material: "Denim",
    season: "Winter",
    image_url: "http://newsvine.com/eu/mi.html",
    description:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "pede lobortis ligula sit amet",
    brand: "Nike",
    category: "Clothing",
    price: 151.82,
    color: "Khaki",
    size: "XL",
    material: "Cotton",
    season: "Spring",
    image_url: "https://forbes.com/justo/morbi/ut/odio/cras.html",
    description:
      "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "purus phasellus",
    brand: "Zara",
    category: "Shoes",
    price: 184.04,
    color: "Pink",
    size: "L",
    material: "Silk",
    season: "Summer",
    image_url:
      "https://nationalgeographic.com/mi/in/porttitor/pede/justo/eu/massa.js",
    description:
      "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.",
    rating: 1,
  },
  {
    id: uuid(),
    product_name: "posuere felis sed lacus",
    brand: "Nike",
    category: "Shoes",
    price: 700.67,
    color: "Maroon",
    size: "S",
    material: "Denim",
    season: "Spring",
    image_url:
      "https://theglobeandmail.com/sapien/iaculis/congue/vivamus/metus.js",
    description:
      "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.",
    rating: 5,
  },
  {
    id: uuid(),
    product_name: "erat quisque erat",
    brand: "Zara",
    category: "Clothing",
    price: 93.04,
    color: "Crimson",
    size: "M",
    material: "Leather",
    season: "Winter",
    image_url: "https://earthlink.net/diam/erat/fermentum/justo.aspx",
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "justo maecenas",
    brand: "Adidas",
    category: "Accessories",
    price: 687.69,
    color: "Puce",
    size: "XL",
    material: "Silk",
    season: "Summer",
    image_url:
      "https://scientificamerican.com/hac/habitasse/platea/dictumst.json",
    description:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.",
    rating: 2,
  },
  {
    id: uuid(),
    product_name: "molestie hendrerit",
    brand: "Zara",
    category: "Shoes",
    price: 519.7,
    color: "Red",
    size: "M",
    material: "Cotton",
    season: "Spring",
    image_url: "http://lycos.com/nonummy/integer.html",
    description:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.",
    rating: 4,
  },
  {
    id: uuid(),
    product_name: "aliquam augue quam",
    brand: "Gucci",
    category: "Shoes",
    price: 379.23,
    color: "Orange",
    size: "XL",
    material: "Denim",
    season: "Fall",
    image_url: "http://marriott.com/vestibulum/ante/ipsum/primis/in.json",
    description:
      "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    rating: 4,
  },
];
